# Theme docs: https://github.com/Yamrc/Kumoi/wiki

site:
  favicon: /favicon.ico
  avatar: /img/avatar.jpg

appearance:
  header:
    logo:
    nav:
      # - title: Home
      #   url: /
      # - title: Archives
      #   url: /archives/
    fixed: true
    banner_background:
  post:
    default_cover: https://i.loli.net/2020/05/01/gkihqEjXxJ5UZ1C.jpg
  effect:
    wowjs: false # TODO :D
  theme:
    dark_mode: auto # TODO: D

components:
  sidebar:
    enable: true
    # widgets order and visibility:
    # - accepted values: author | toc | recent_posts | categories | tags | archives
    # - render order follows this list; unknown names are ignored
    # - "toc" only appears on post pages
    # - supports either:
    #   - simple form: ["author", "toc", ...]
    #   - object form: [{ name: "toc" }, { name: "recent_posts" }]
    widgets:
      - author
      - toc
      - recent_posts
      - categories
      - tags
      - archives
    recent_limit: 3
  author:
    background:
      light: /img/light.jpg
      dark: /img/dark.jpg
    social:
      # Font Awesome format: "link||title||color"
      # example:
      #
      # "fab fa-github": "https://github.com/user||GitHub||#333"
      # "fab fa-twitter": "https://twitter.com/user||Twitter||#1DA1F2"
    author_button:
      enabled: false
      icon: fab fa-github
      text: Follow me
      url: https://github.com/user

plugins:
  # Search: requires hexo-generator-searchdb
  search: false
  comments:
    # Comments: choose one of twikoo | giscus
    # Docs: Twikoo https://twikoo.js.org/ Â· Giscus https://giscus.app
    provider: # twikoo | giscus
    twikoo:
      # Backend URL
      env_id:
    giscus:
      # Generate the following at https://giscus.app and paste here
      repo:
      repo_id:
      category:
      category_id:
      reactions_enabled: true
      mapping: pathname
      language: zh-CN # leave empty to fallback to Hexo config
  pjax:
    # PJAX: disable if third-party scripts break
    enable: true
  analytics:
    # Analytics: cloudflare | umami (or leave empty to disable)
    provider: # cloudflare | umami
    cloudflare:
      token:
    umami:
      # Docs: https://umami.is/docs
      site_id:
      server_url:
